### ISSUE TITLE
Possible with Typer app not in a decorator?

### ISSUE THREAD

**Issue by vegarsti** [Textualize/trogon#10]
This is quite possibly a stupid question, but is there a way to wrap this in a Trogon TUI? I instantiate my `typer.Typer` app like this, as shown in that project's README

```
app = typer.Typer()
```

Is there a way to wrap that in a Trogon TUI?

**Comment by alberto-of** [comment]
I have the same problem.

**Comment by davep** [comment]
Perhaps [this will help here](https://twitter.com/renan_r_santoss/status/1660305963839102976?s=46&t=cybZxk_7txtYkco8G7L3Dg)?

**Comment by vegarsti** [comment]
Yes! Thank you so much!
