### ISSUE TITLE
Search function for Trogon

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/trogon#19]
A search box (at the top?) which refines the list of options.

The search should match against the help text and the switch.

For inspiration, look at Chrome settings.

**Comment by simonw** [comment]
I kind of want this for the list of commands - `sqlite-utils` has 45 now:

<img width="1304" alt="image" src="https://github.com/Textualize/trogon/assets/9599/6ee53b58-6d5c-471b-ab29-d7c44315bf32">

**Comment by darrenburns** [comment]
@simonw I agree that'd be useful, I've had the same thought while using it (I've been using `sqlite-utils` heavily as a test environment for trogon, as it seems to cover a huge portion of the Click API surface). If you want to use a command near the bottom, reaching for the mouse feels like the only reasonable option right now.
