### ISSUE TITLE
Add version 0.4 release on GitHub, to allow Debian package to be created

### ISSUE THREAD

**Issue by EdwardBetts** [Textualize/trogon#37]
I'd like to package trogon for Debian.

To make a Debian package I need a tarball that includes the test suite.

PyPI. has a tarball for trogon version 0.4 without the test suite, GitHub has version 0.3 with the tests.

It would be great if somebody could create a GitHub release for version 0.4 or add the tests to the tarball on PyPI.

**Comment by darrenburns** [comment]
Sorry about that - done!

**Comment by EdwardBetts** [comment]
Thanks. I'll work on a Debian package. Trogon needs a newer version of Textualize than the one in Debian. I'm going to investigate what needs to be done to update the Textualize Debian package to the latest version.
