### ISSUE TITLE
trogon tui fallback

### ISSUE THREAD

**Issue by cariaso** [Textualize/trogon#48]
I'd like to use trogon when it's available, and fail gracefully when it is not. It seems this should be sufficient

```
try:
    from trogon import tui
except ImportError:
    tui = PassThroughDecorator()

@tui()
@click.group(...)
def cli():
    ...

```

but I've been unable to come up with a suitable `PassThroughDecorator`?

**Comment by willmcgugan** [comment]
Would this work?

```python
tui = lambda func: func
```

**Comment by cariaso** [comment]
yup. my sincere thanks for the answer, and much general python awesomeness

**Comment by cariaso** [comment]
I take back the 'yup'. That does not handle the parens.

```
import click
try:
    from trogon import tui
except ModuleNotFoundError:
    print("using noop trogon tui")
    tui = lambda func: func

@tui()
@click.group(...)
def cli():
    ...

```

using noop trogon tui
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/path/to/__main__.py", line 13, in <module>
    @tui()
     ^^^^^
TypeError: <lambda>() missing 1 required positional argument: 'func'


the code you provided does work for
```
@tui
```
but not
```
@tui()
```

**Comment by fresh2dev** [comment]
ref: https://stackoverflow.com/a/73275170

```python
try:
    from trogon import tui
except ModuleNotFoundError:
    def tui(f=None, *args, **kwargs):
        def decorator(func):
            return func

        if callable(f):
            return f
        else:
            return decorator
```

**Comment by cariaso** [comment]
confirmed as successful. my thanks to @fresh2dev
