### ISSUE TITLE
Clarify the licence that Trogon is released under

### ISSUE THREAD

**Issue by davep** [Textualize/trogon#49]
As pointed out [over on Discord](https://discord.com/channels/1026214085173461072/1033754296224841768/1123586225417244733), there is no licence file in the repository, it's not made clear in the README what the licence is, and by extension the presentation of the repo here on GitHub doesn't make clear the licence.

It is [indicated in the project file](https://github.com/Textualize/trogon/blob/25eab1eb7b5d38fb84126bc5c4ff77c37f557baf/pyproject.toml#L8) but nowhere else.

**Comment by chrisjsewell** [comment]
Indeed, I would like to also distribute on conda-forge, in which case a license file is required in the source distribution

**Comment by kratsg** [comment]
> Indeed, I would like to also distribute on conda-forge, in which case a license file is required in the source distribution

I would also like to have it on conda-forge too. https://twitter.com/kratsg/status/1669231846700511232

**Comment by TkTech** [comment]
@davep  This can be closed with the LICENSE file committed today :)

**Comment by chrisjsewell** [comment]
Cheers!

**Comment by davep** [comment]
I don't personally have the ability to make a release. Do note though that doing so won't change the licence status.

**Comment by kratsg** [comment]
> Do note though that doing so won't change the licence status.

Oh - but I do see it listed as an MIT license. Most places, such as conda, expect the LICENSE to be packaged up in the tarball on `pypi` so a release should include that. Fair enough. I'll just package from the GitHub repo for now and keep an eye out for a new release in the future.
