### ISSUE TITLE
[Not Issue] What typeface is used in the screenshots?

### ISSUE THREAD

**Issue by scottmudge** [Textualize/trogon#6]
As the title notes, this isn't directly related to the project, but I love the typeface used I your screenshots. What is it? Tried auto-detecting it, but couldn't figure out what it was. 

Awesome project by the way!

**Comment by willmcgugan** [comment]
Beautiful. Isn’t it? It’s Berkeley Mono.

**Comment by scottmudge** [comment]
It certainly is, ticks all my boxes. Thanks for the ID, appreciate it!
