### ISSUE TITLE
How hard would it be to support golang kong?

### ISSUE THREAD

**Issue by zapman449** [Textualize/trogon#75]
https://github.com/alecthomas/kong

Curious if this is python exclusive or if multi-language is possible.

**Comment by gaby** [comment]
@zapman449 Mostly python, it depends heavily on `textual` and `click` which are also python based.

**Comment by daneah** [comment]
Given open or past issues and comments asking about support for at least:

- Typer
- argh
- argparse
- python-fire
- golang kong

It seems that #43 captures the more generally maintainable way forward.
