### ISSUE TITLE
WEB UI?

### ISSUE THREAD

**Issue by askerrit** [Textualize/trogon#79]
Is it possible to use a web UI from Trogon?

**Comment by daneah** [comment]
Hey @askerrit, for my benefit can you elaborate some on your question here? What would you like to be able to do, and how do you imagine it working with Trogon?

**Comment by Wytamma** [comment]
It's possible! I'm working on a project based on Trogon that uses Gradio to build a web UI from a click CLI -> https://github.com/Wytamma/GUIGAGA

**Comment by daneah** [comment]
@Wytamma nice project! To clarify, Trogon doesn't support a web UI itself, so something like GUIGAGA or rolling your own will be necessary at this time.
