### ISSUE TITLE
Need maintainers?

### ISSUE THREAD

**Issue by daneah** [Textualize/trogon#86]
Signals point to this project being unmaintained, and I'm curious if y'all are open to additional maintainers.

**Comment by willmcgugan** [comment]
Hi Dane. Not entirely unmaintained, but we are stretched thing right now. Are you offering?

@darrenburns What do you think?

**Comment by daneah** [comment]
I might be interested, yes! Wanted to get a better sense of the situation first. I know you both are very busy 😄

**Comment by darrenburns** [comment]
@willmcgugan I think it makes sense.

**Comment by willmcgugan** [comment]
@daneah If you are up for it, happy to make you a maintainer.

Might also be worth having a chat. Zoom call next week?

**Comment by daneah** [comment]
@willmcgugan @darrenburns I appreciate the openness to it 😄 I should have some time to discuss toward the tail end of next week; I'll be AFK through mid-week.

**Comment by gaby** [comment]
Biggest thing right now is merging this https://github.com/Textualize/trogon/pull/83

When a new user installs `trogon` the whole footer doesnt work at all. I had to pin `textual` to `<0.61.0`.

**Comment by gaby** [comment]
@willmcgugan @darrenburns @daneah Any updates on this? It's currently impossible to use `Trogon` with latest `textual`, until https://github.com/Textualize/trogon/pull/83 is merged

**Comment by willmcgugan** [comment]
Will look at this v soon.

@daneah Are you on the Textual discord? Can send you a Zoom invite for a quick chat.

**Comment by daneah** [comment]
@willmcgugan not presently but I can be there soon

**Comment by daneah** [comment]
I'm there now; I should be free after 11:00 ET on Friday if that works well, otherwise I have a couple of spotty hours tomorrow.

**Comment by gaby** [comment]
This probably needs to be opened again, progress has staled and trogon is not up to date with `textual`
