### ISSUE TITLE
Trouble adding trogon TUI to typer app

### ISSUE THREAD

**Issue by peterjc** [Textualize/trogon#94]
I tried the documented approach with ``init_tui``, but couldn't get it to add ``tui`` to the command.

However adding this did work (spotted somewhere on the issue tracker, I lost the link though):

```python
@app.command()
def tui(ctx: typer.Context):
    from typer.main import get_group
    from trogon import Trogon
    Trogon(get_group(app), click_context=ctx).run()
```

Using typer 0.12.5, trogon 0.6.0, Python 3.12, macOS

Perhaps a typer example under [``examples/``](https://github.com/Textualize/trogon/tree/main/examples) would help?

**Comment by daneah** [comment]
Thanks for reporting @peterjc; can you see if #96 helps you resolve this or if you're still having challenges with it?

**Comment by peterjc** [comment]
That did work for me, thank you.

Sadly I don't think I kept my earlier attempts to work out what I was doing wrong in hindsight.

**Comment by daneah** [comment]
@peterjc no worries, glad to hear it's working for you!
